version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:213326868914:task-definition/hello-world-ci-cd-task:1"
        LoadBalancerInfo:
          ContainerName: "hello-world-ci-cd"
          ContainerPort: "80"
        PlatformVersion: "LATEST"